### ISSUE TITLE
Some problem about the twitter dataset in paper Learning Multiview Embeddings of Twitter Users

### ISSUE THREAD

**Issue by JyiHUO** [abenton/wgcca#3]
Hi, I want to reproduce your paper. However, I found that the embedding dataset only contains four views without target data.  So I can not train a classification model, such as svm or decision tree using this dataset without label. So could you provide the dataset for me. Any help will be very useful, thank you.

**Comment by abenton** [comment]
Full views can be found here http://www.cs.jhu.edu/~mdredze/datasets/multiview_embeddings/ (described in README).

Will post user IDs for hashtag/follower prediction tasks to the website shortly.

**Comment by JyiHUO** [comment]
Thank you for your help.😁

**Comment by JyiHUO** [comment]
Also, there are some problems with the data. When I debug your code to see what the data going on:

![image](https://user-images.githubusercontent.com/16526817/42883574-871a10c4-8ace-11e8-9a01-d529c6e8c7b5.png)

The data showed above is one row for a twitter user.  Certainly, the first view is USER ID. However, I found that there are only four embedding views, and the other four views all '1'.  What is that name of each view ? It doesn't match with these column name below showed in this [like](http://www.cs.jhu.edu/~mdredze/datasets/multiview_embeddings/):

- UserID
- EgoTweets
- MentionTweets
- FriendTweets
- FollowerTweets
- FriendNetwork
- FollowerNetwork

**Comment by abenton** [comment]
Ah, those "1"s are indicator features for whether the view for this user is missing data (e.g. we were not able to collect their friends' tweets).  If a view is missing data, then this would be a "0".  The views themselves are the following four fields of 1000 floats each.  These indicator features are used to initialize $K$ in the wgcca objective.  Will update data description on data page.

Are you looking at the sample data included in the repository or that shared here:
[http://www.cs.jhu.edu/~mdredze/datasets/multiview_embeddings/user_6views_tfidf_pcaEmbeddings_userTweets+networks.tsv.gz](http://www.cs.jhu.edu/~mdredze/datasets/multiview_embeddings/user_6views_tfidf_pcaEmbeddings_userTweets+networks.tsv.gz)?

The sample data only includes a sample of Twitter users' text views.

**Comment by JyiHUO** [comment]
Great thanks 😉. Hope that I can reproduce your result.

**Comment by abenton** [comment]
Updated data description page with user IDs for user engagement and friend prediction.
